io:
    output_dir: ./

interface:
    show_pp: True
    render_cube: True
    show_ROI: True
    show_withour_ROI: True
    show_original: False
    print_online: True
    width: 400

K:
    F:
        min_val: 10
        max_val: 5000
        step: 1e-1
    CX:
        min_val: 0
        max_val: 1000
        step: 1
    CY:
        min_val: 0
        max_val: 1000
        step: 1

D:
    D0:
        min_val: -15
        max_val: 15
        step: 1e-2
    D1:
        min_val: -15
        max_val: 15
        step: 1e-2
    D2:
        min_val: -5
        max_val: 5
        step: 1e-2
    D3:
        min_val: -5
        max_val: 5
        step: 1e-2
    D4:
        min_val: -3
        max_val: 3
        step: 1e-3

T:
    X:
        max_val: 1
        min_val: -1
        step: 1e-3
    Y:
        max_val: 1
        min_val: -1
        step: 1e-3
    Z:
        max_val: 1
        min_val: -1
        step: 1e-3

R:
    yaw:
        max_val: 3.14
        min_val: -3.14
        step: 1e-3
    pitch:
        max_val: 3.14
        min_val: -3.14
        step: 1e-3
    roll:
        max_val: 3.14
        min_val: -3.14
        step: 1e-3

CUBE:
    length_X:
        max_val: 5
        min_val: 1
        step: 1e-1
    length_Y:
        max_val: 5
        min_val: 1
        step: 1e-1
    length_Z:
        max_val: 5
        min_val: 1
        step: 1e-1
    QX:
        max_val: 100
        min_val: -100
        step: 1e-1
    QY:
        max_val: 100
        min_val: -100
        step: 1e-1
    QZ:
        max_val: 100
        min_val: 0
        step: 1e-1
